[ERROR] 2021-03-06 08:00:17,554 | /home/hp/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: characters_written
Traceback (most recent call last):
  File "/home/hp/frappe-bench/apps/frappe/frappe/utils/error.py", line 167, in collect_error_snapshots
    os.remove(fullpath)
PermissionError: [Errno 13] Permission denied: './gne3.gndec.ac.in/error-snapshots/2021-03-05 22:44:16.999596-106.192.22.30-3af.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hp/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/hp/frappe-bench/apps/frappe/frappe/utils/error.py", line 127, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
